####Crear usuario
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "javi",
    "email": "javi@u-tad.com",
    "nickname":"javichu",
    "sport":"futbol,padel",
    "schedule":"11:00-12:00",
    "password":"javiScript",
    "conf_password":"javiScript"
}
### login usuario
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "username": "javi@u-tad.com",
    "password":"javiScript"
}


### editar usuario
POST http://localhost:3000/api/changeParams HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImFsZXhmcDIwMDEiLCJpYXQiOjE2Nzg5ODQwNjIsImV4cCI6MTY3ODk5MTI2Mn0.wIDfhpU51_NOurYZL5VWY1fAcL0Dvq6WxpVENvtRyCg

{
    "param":"nickname",
    "valor":"alexfp2001"
}


### todos usuario
GET http://localhost:3000/auth/getUsers HTTP/1.1
Content-Type: application/json

######