####Crear usuario
POST http://localhost:3000/auth/register HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "jav2i",
    "email": "javi2@u-tad.com",
    "nickname":"javichu2",
    "sport":"futbol,padel",
    "schedule":"11:00-12:00",
    "password":"javiScript",
    "conf_password":"javiScript"
}
### login usuario
POST http://localhost:3000/auth/login HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "username": "javi@u-tad.com",
    "password":"javiScript"
}





### todos usuario
GET http://localhost:3000/auth/getUsers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImphdmljaHUiLCJpYXQiOjE2ODE0NjYwOTEsImV4cCI6MTcxNzQ2MjQ5MX0.0EIrZmzCkrN320RWYdqsd6xHdhpmBsrr-4hzbNxzPcc
######crear actividades
POST http://localhost:3000/activity/createActivity HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImphdmljaHUiLCJpYXQiOjE2ODEzNzAwODYsImV4cCI6MTY4MTM3NzI4Nn0.leKq5RBTUT5kjON_H6aMvILUJgQBDEnfONXDk7MuIsY

{
  "name": "DAtas vs cyber",
  "description": "Partido de furbol",
  "sport": "Fútbol",
  "date": "2023-04-05T12:00:00Z",
  "privacity": true,
  "max_plazas": 20,
  "status": true,
  "result": "",
  "place": "Futbol sala utad"
}
### todos las actividades
GET http://localhost:3000/activity/getActivitys HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsIR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImphdmljaHUiLCJpYXQiOjE2ODE4MTYzNTcsImV4cCI6MTcxNzgxMjc1N30.spwbV-WHN13dEX7N0D59TzkA3YkxvuZVCPRpGIv9vPE

### todos las actividades
POST http://localhost:3000/activity/suscribeActivity HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImphdmljaHUiLCJpYXQiOjE2ODA5NTUxNjksImV4cCI6MTY4MDk2MjM2OX0.pIhIghomzvSg7wq7CSTNGzHXTj-Skoo2yDbLWcCwouU

{
  
  "activityId": 1,
  "permission": 1
}
### todos las actividades de un usuario
GET http://localhost:3000/activity/getMyActivitys HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImphdmljaHUiLCJpYXQiOjE2ODEzNzAwODYsImV4cCI6MTY4MTM3NzI4Nn0.leKq5RBTUT5kjON_H6aMvILUJgQBDEnfONXDk7MuIsY

####create team##########

POST http://localhost:3000/team/createTeam HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImphdmljaHUiLCJpYXQiOjE2ODE5NzU0MTEsImV4cCI6MTcxNzk3MTgxMX0.koSaCMtFcdAYCj8pCXdqc5rNX3OK_4riROVLbrOC7GA

{
  "name":"Game team",
  "sport":"Football",
  "logo":"logo.png",
  "max_players_team":8
}


#####get teams####
GET http://localhost:3000/team/getTeams HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImphdmljaHUiLCJpYXQiOjE2ODE5NzU0MTEsImV4cCI6MTcxNzk3MTgxMX0.koSaCMtFcdAYCj8pCXdqc5rNX3OK_4riROVLbrOC7GA

##########inscribe into a team###########
POST  http://localhost:3000/team/joinTeam
Content-Type: application/json
api_key: Api-publica-123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImphdmljaHUyIiwiaWF0IjoxNjgxOTc1NTU2LCJleHAiOjE3MTc5NzE5NTZ9.6MOk8FqX6Bpw_p52VjVDZok9r21dW-qtHMNwbJrlHsA

{
 "id":9
}

#####get my team####
GET http://localhost:3000/team/myTeams HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImphdmljaHUyIiwiaWF0IjoxNjgxOTc3NjA5LCJleHAiOjE3MTc5NzQwMDl9.x2k_oTKtFPWvyBbRAeO7Q2xuAjiD_Kr9f2NcbYwV2Vs




