POST http://localhost:3000/api/createUser HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "nombre": "Alex2",
    "email": "alexfdeaszperera@hotmail.com",
    "nickname":"alexfp22001",
    "deporte":"futbol",
    "horario":"13:00-14:00",
    "password":"Alex1234"
}
###
POST http://localhost:3000/api/login HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "email": "alexfdeaszperera@hotmail.com",
    "password":"Alex1234"
}